@startuml

class Cliente {
}

class Caja {
}

class Cola {
}

class Estadisticas {
}

class GestorCajas {
}

class Jornada {

}

' Relaciones con tipo específico
Caja --> Cliente : usa
Cola *-- Cliente : contiene
GestorCajas *-- Caja : compone
GestorCajas ..> Cola : usa
GestorCajas ..> Estadisticas : usa
Jornada --> Cola : tiene
Jornada --> GestorCajas : tiene
Jornada --> Estadisticas : tiene

@enduml
