@startuml

class Mundo {
}
class Caja {
}
class Cola {
}
class Cliente {
}
class Productos {
}
class Estadisticas {
}


Mundo --> Caja : "Usa varias"
Caja --> Cliente : "Atiende"
Cliente *-- Productos : "Tiene"
Cliente --o Cola : "Forma"
Caja ..> Cola : "Gestiona dependiendo de"
Estadisticas --o Cliente : "Registra varios"

@enduml

