@startuml

class Jornada {
}
class Caja {
}
class Cola {
}
class Productos {
}

Jornada --> Caja : "Abre"
Jornada --> Cliente : "Sirve"
Cliente --> Productos : "Tiene"
Cliente --> Cola : "Forma"
Caja .. Cola : "Gestiona dependiendo de"

@enduml
