@startuml

object Superficie1
object Zona1
object Zona2
object Aspiradora1
object Mueble1
object Gato1
object Celda1

' Relación entre objetos
Superficie1 *-- Zona1 : "está formada por"
Superficie1 *-- Zona2 : "está formada por"

Zona1 o-- Gato1 : "puede contener"
Zona1 --> Mueble1 : "tiene asociado"
Zona2 --> Mueble1 : "tiene asociado"

Aspiradora1 --> Zona1 : "se mueve en"
Aspiradora1 --> Zona1 : "limpia"
Aspiradora1 --> Mueble1 : "detecta y evita"

Gato1 --> Celda1 : "ensucia"

@enduml
