@startuml

class Simulacion {
}
class Cola {
}
class Caja {
}
class Estadisticas {
}
class GestorCajas {
}
class Cliente {
}

Simulacion --> Cola : "crea"
Simulacion --> Caja : "crea"
Simulacion --> Estadisticas : "permite acceso"
Simulacion --> GestorCajas : "crea"
GestorCajas -> Caja : "gestiona estado"
Cola --> Cliente : "almacena"
Caja --> Cliente : "atiende"
Item <-- Caja : "procesa"
Cliente --> Item : "trae"
@enduml