object "heman: Guerrero" as heman{
    energia = 20
    
}

object "arma: Arma" as arma {
    daño = 4
    porcentajeExito = 50%
}

object "dracula: Vampiro" as dracula{
    energia = 10
}

object "mordida: Mordida" as mordida {
    daño = 2
    porcentajeExito = 50%
}

object batalla

batalla *-d- heman
batalla *-d- dracula

heman *-- arma
dracula *-- mordida