@startuml DdO

hide circle
hide empty members

class Mundo {
+ horario: "12:40"
}

class Universidad {
    + capacidad: "30"
}

class Persona {
    + nombre: "Paco"
    + deseaIr: "2"
}

class Ascensor {
    + capacidad: "3"
    + plantaActual: "-1"
    + movimiento: "ascendente"
}

class Planta {
    + numero: "0"
}

Mundo *-- Persona : genera
Mundo *-- Universidad : crea

Universidad *-- Planta : contiene
Universidad o-- Persona : acoge
Universidad *-- Ascensor : posee

Persona o-- Ascensor : utiliza
Ascensor -- Planta : comunica
Persona o-- Planta : está en

@enduml
@startuml DdC

hide circle
hide empty members

class Mundo {
+ horario: "12:40"
}

class Universidad {
    + capacidad: "30"
}

class Persona {
    + nombre: "Paco"
    + deseaIr: "2"
}

class Ascensor {
    + capacidad: "3"
    + plantaActual: "-1"
    + movimiento: "ascendente"
}

class Planta {
    + numero: "0"
}

Mundo *-- Persona : genera
Mundo *-- Universidad : crea

Universidad *-- Planta : contiene
Universidad o-- Persona : acoge
Universidad *-- Ascensor : posee

Persona o-- Ascensor : utiliza
Ascensor -- Planta : comunica
Persona o-- Planta : está en

@enduml
