object Superficie {
  ancho = 25
  alto = 10
  zonas = [Zona1, Zona2, ..., ZonaN]
  muebles = [Sofa, Mesa]
}

object Zona1 {
  x = 2
  y = 3
  nivel_suciedad = 3
}

object Aspiradora {
  x = 4
  y = 5
  bateria = 75
  bolsa_basura = 30
}

object Mueble {
  x = 6
  y = 6
}

object Gato {
  x = 3
  y = 2
  pasos_restantes = 15
}
