@startuml
hide empty description

[*] --> FueraUniversidad : inicio
FueraUniversidad --> EnUniversidad : entra a la universidad

EnUniversidad --> EnPlanta : se encuentra en una planta

EnPlanta --> SolicitandoAscensor : decide usar el ascensor
SolicitandoAscensor --> EsperandoAscensor : espera que llegue
EsperandoAscensor --> EnAscensor : ascensor llega y entra
EnAscensor --> SeleccionandoPlanta : elige a qué planta ir
SeleccionandoPlanta --> EnMovimiento : el ascensor se mueve
EnMovimiento --> EnPlanta : llega a la nueva planta y sale

EnPlanta --> SaliendoUniversidad : finaliza su jornada y se dirige a la salida
SaliendoUniversidad --> FueraUniversidad : sale definitivamente

FueraUniversidad --> [*] : fin del proceso

@enduml
