@startuml diagramaDeClases
hide empty members
hide circles

class Maquina
class FormaDePago
class Pago
class Usuario
class Productos
class Celdas
class Compra
class Empleado

Maquina --> FormaDePago : maneja
Maquina *-- Celdas
Maquina --> Compra : procesa
Celdas o-- Productos
Usuario -U-> Celdas : selecciona 
Usuario --> Pago : efectua
Pago --> FormaDePago 
Compra --* Pago
Empleado .U..> Maquina : abastece
FormaDePago <|-- Efectivo
FormaDePago <|-- Tarjeta
FormaDePago <|-- Monedero

@enduml
