@startuml diagramaDeClases
hide empty members
hide circles

class Maquina
class Pago
class Efectivo
class Usuario
class Productos
class Celdas
class Empleado

Maquina *-- Celdas
Celdas o-- Productos
Usuario -U-> Celdas : selecciona 
Usuario --> Pago : efectua 
Empleado .U..> Maquina : abastece
Pago --> Efectivo : maneja

@enduml
