@startuml
package "moduloMaquina" {
  class Maquina
}

package "moduloInventario" {
  class Celda
  class Producto
}

package "moduloCaja" {
  class Caja
}

package "moduloPago" {
  interface Pago
  class Efectivo
  class Tarjeta
}

package "moduloUsuario" {
  class Usuario
}

package "moduloEmpleado" {
  class Empleado
}

Maquina o-- "1..*" Celda : contiene
Maquina o-- Caja
Maquina --> Usuario
Maquina ..> Pago

Celda *-- Producto
Efectivo ..> Caja
Usuario o-- Tarjeta
Usuario o-- Efectivo

Empleado ..> Caja : recargar / vaciar
Empleado ..> Celda : cargar productos

Tarjeta ..|> Pago
Efectivo ..|> Pago
@enduml