@startuml
hide empty members
hide circle
abstract "Maquina:Maquina1"{
    id: 1
    Ubicacion: Cafetería
    Estado: "activo"
}

class "Celdas:Celda12"{
    id: 12
    id_maquina : 1
    Capacidad: 10
    Precio: 1.95
}

class "Productos:Producto1"{
    id: 3
    Nombre: Kinder Bueno
    Fecha_expiración: 12/11/2025
    id_celda: 12
}


class "Usuario:Usuario1"{
    id: 1
    Nombre: "Diego"
}


class "Pago:Pago1"{
    id: 1
    Monto: 1.95
    Estado: "Pago Exitoso"
}

class "Empleado:Empleado1"{
   id: 1
   Nombre: "Carlos"
   Acciones_realizadas: "Abastecer"

}

class "PagoEfectivo:PagoEfectivo1"{
    Saldo: "Suficiente"
    Cantidad_billetes: 0 
    Cantidad_monedas: 2 
}




"Maquina:Maquina1" --> "Celdas:Celda12" : tiene
"Celdas:Celda12" --> "Productos:Producto1" : contiene
"Usuario:Usuario1" -U-> "Celdas:Celda12" : selecciona
"Usuario:Usuario1" --> "Pago:Pago1" : efectua
"Empleado:Empleado1" -U-> "Maquina:Maquina1" : abastece
"Pago:Pago1" -D-> "PagoEfectivo:PagoEfectivo1" : maneja


@enduml
